<?php
/**
 * A stand-in for the SpectroCoin merchant API as this extension talks to it.
 *
 * Magento is the one plugin still on the LEGACY flow: form-encoded requests,
 * and callbacks authenticated by an RSA signature rather than by fetching the
 * order back over an authenticated channel. So this stub differs from the
 * others in two ways:
 *
 *   POST /api/merchant/1/createOrder   form-encoded, answers JSON
 *   GET  /files/merchant.public.pem    the certificate the extension verifies
 *                                      callback signatures against
 *
 * Serving that certificate is why the stub answers as spectrocoin.com: the
 * location is hardcoded in the client, so the extension fetches it exactly as
 * it ships. The matching private key is generated by the test, which uses it to
 * sign the callbacks it delivers.
 *
 * Plus a control surface the test drives it with, namespaced so it cannot be
 * confused for part of the contract:
 *   GET  /__test/requests   everything the extension has sent us
 *   POST /__test/reset      forget all state
 */

declare(strict_types=1);

const STATE = '/tmp/stub-state.json';

function state(): array
{
    return file_exists(STATE)
        ? (json_decode((string) file_get_contents(STATE), true) ?: [])
        : ['orders' => [], 'requests' => []];
}

function save(array $s): void
{
    file_put_contents(STATE, json_encode($s, JSON_PRETTY_PRINT));
}

function send(int $code, array $payload): never
{
    http_response_code($code);
    header('Content-Type: application/json');
    echo json_encode($payload);
    exit;
}

$path   = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?: '/';
$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$s      = state();

// Requests from the extension are recorded so the test can assert on what it
// actually sent. The control surface and the healthcheck are not the extension,
// and recording them would bury the traffic under test.
if (!str_starts_with($path, '/__test/')) {
    $s['requests'][] = [
        'method'     => $method,
        'path'       => $path,
        'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? '',
        'body'       => (string) file_get_contents('php://input'),
        'post'       => $_POST,
    ];
    save($s);
}

// ---------------------------------------------------------------- control ---
if ($path === '/__test/reset') {
    save(['orders' => [], 'requests' => []]);
    send(200, ['ok' => true]);
}

if ($path === '/__test/requests') {
    send(200, $s['requests']);
}

// ------------------------------------------------------------ certificate ---
// The extension fetches this on every callback to verify the signature.
if ($path === '/files/merchant.public.pem') {
    header('Content-Type: application/x-pem-file');
    readfile('/certs/callback-public.pem');
    exit;
}

// ----------------------------------------------------------------- orders ---
if (str_ends_with($path, '/createOrder')) {
    if ($method !== 'POST') {
        send(405, ['error' => 'method not allowed']);
    }

    // The legacy API is form-encoded and signs the request; the stub records
    // what arrived rather than re-verifying our own signature.
    $orderId = (string) ($_POST['orderId'] ?? '');
    $uuid    = bin2hex(random_bytes(8));

    $s['orders'][$uuid] = [
        'uuid'            => $uuid,
        'orderId'         => $orderId,
        'receiveAmount'   => (string) ($_POST['receiveAmount'] ?? '0'),
        'receiveCurrency' => (string) ($_POST['receiveCurrency'] ?? ''),
        'payAmount'       => (string) ($_POST['payAmount'] ?? '0'),
        'payCurrency'     => (string) ($_POST['payCurrency'] ?? ''),
        'callbackUrl'     => (string) ($_POST['callbackUrl'] ?? ''),
    ];
    save($s);

    // Shape mirrored from CreateOrderResponse.
    header('Content-Type: application/json');
    echo json_encode([
        'orderRequestId' => 1001,
        'orderId'        => $orderId,
        'depositAddress' => 'bc1qstubstubstubstubstubstubstubstubstub',
        'payAmount'      => (float) ($_POST['payAmount'] ?? 0),
        'payCurrency'    => $_POST['payCurrency'] ?? 'BTC',
        'receiveAmount'  => (float) ($_POST['receiveAmount'] ?? 0),
        'receiveCurrency'=> $_POST['receiveCurrency'] ?? 'EUR',
        'validUntil'     => '2099-01-01T00:00:00Z',
        'redirectUrl'    => 'https://spectrocoin.com/pay/' . $uuid,
    ]);
    exit;
}

send(404, ['error' => 'not found', 'path' => $path]);
